package consultationbookingsystem;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class LguiEditConsultation extends javax.swing.JFrame {
    
    private LguiAppointment appointment;
    private Lecturer current;
    private Consultation consultation;
    private Consultation x;
    private LguiEditConsultation_Venue select_venue;
    
        
    public void setLecSelectVenue(LguiEditConsultation_Venue a){
        select_venue = a;
    }
        
    boolean window = false;
    
    public void setBoolean(Boolean y){
        window = y;
    }
       
    public void setUser(Lecturer x, Consultation z){
        current = x;
        consultation = z;
     
        for(int i=0; i<current.getCons().size(); i++){
            Consultation zz = current.getCons().get(i);
            
            if(consultation.getDay().equals(zz.getDay()) && consultation.getTime().equals(zz.getTime()) && consultation.getVenue().equals(zz.getVenue())){
                lblVenue.setText(zz.getVenue());
                String date = zz.getDay();
                                                    
                try{        
                                    
                    SimpleDateFormat dateFormatterrr = new SimpleDateFormat("E, y-M-d 'at' h:m:s a z");   
                    dateFormatterrr = new SimpleDateFormat("d/M/y");     
                    Date bb = dateFormatterrr.parse(date);             
                    dateChooser.setDate(bb); 
                                    
                }catch(ParseException pe){
                                    
                }
                
                cboTime.setSelectedItem(zz.getTime());
                
            }
        }
    }
    
    public LguiEditConsultation() {
        initComponents();
                
        JOptionPane.showMessageDialog(this, "You Cannot Open Like This","You Cannot Open Like This!", JOptionPane.ERROR_MESSAGE);
        window = false;
    }
        
    public LguiEditConsultation(LguiAppointment a) {
        initComponents();
        
        appointment = a;
        appointment.setLecEditConsultation(this);
        
        window = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        cboTime = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        lblVenue = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Venue:");

        jLabel2.setText("Date:");

        jLabel3.setText("Time:");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30" }));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblVenue.setText("jLabel4");

        jButton3.setText("Select");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(cboTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblVenue)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            DateFormat dff = new SimpleDateFormat("d/M/yyyy");
            String newVenue = lblVenue.getText();
            String newDate = dff.format(dateChooser.getDate());
            String newTime = cboTime.getSelectedItem().toString();
            boolean abc = true;

            SimpleDateFormat dateFormatterrr = new SimpleDateFormat("E, y-M-d 'at' h:m:s a z");
            dateFormatterrr = new SimpleDateFormat("d/M/y");
            DateFormat df = new SimpleDateFormat("d/M/yyyy");
            String a = df.format(dateChooser.getDate());
            Date bb = dateFormatterrr.parse(a);
            Date ab = new Date();

            if(bb.before(ab)){
                JOptionPane.showMessageDialog(this, "SELECT THE DATE BEFORE TODAY!","PLEASE SELECT THE DATE BEFORE TODAY!", JOptionPane.ERROR_MESSAGE);
            }else if(newVenue.trim().isEmpty() || newDate.trim().isEmpty() || newTime.trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "PLEASE FILL ALL THE FIELD!","PLEASE FILL ALL THE FIELD!", JOptionPane.ERROR_MESSAGE);
            }
            else{
                for(int i = 0; i<current.getCons().size(); i++){
                    
                    x = current.getCons().get(i);
                    
                    if(newVenue.equals(x.getVenue()) && newTime.equals(x.getTime()) && newDate.equals(x.getDay())){
                        JOptionPane.showMessageDialog(this, "THE CONSULTATON IS EXIST!","THE CONSULTATON IS EXIST!", JOptionPane.INFORMATION_MESSAGE);
                        abc = false;
                        break;
                    }else if(newTime.equals(x.getTime()) && newDate.equals(x.getDay())){
                        JOptionPane.showMessageDialog(this, "THE TIME & DATE GOT CONSULTATION!","THE TIME & DATE GOT CONSULTATION!", JOptionPane.INFORMATION_MESSAGE);
                        abc = false;
                        break;
                    }else{
                        abc = true;
                    }
                }
                if(abc == true){
                    for(int i = 0; i<current.getCons().size(); i++){
                        Consultation y = current.getCons().get(i);
                                            
                        if(consultation.getDay().equals(y.getDay()) && consultation.getTime().equals(y.getTime()) && consultation.getVenue().equals(y.getVenue())){
                            consultation.setDay(dateFormatterrr.format(bb));  
                            consultation.setTime(newTime); 
                            consultation.setVenue(newVenue);
                            JOptionPane.showMessageDialog(this, "EDIT SUCCESSFULLY!","EDIT SUCCESSFULLY!", JOptionPane.INFORMATION_MESSAGE);
                            break;
                        }
                    }
                }
            }

        }catch(ParseException cd){
            JOptionPane.showMessageDialog(this, "DATE FAILED TO CONVERT!","DATE FAILED TO CONVERT!", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "PLEASE SELECT A DATE!","PLEASE SELECT A DATE!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        appointment.setUser(current, consultation);
        appointment.setBoolean(true);
        appointment.setVisible(true);
        lblVenue.setText(null);
        dateChooser.setDate(null);
        cboTime.setSelectedItem(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                
        select_venue.setUser(current, consultation);
        select_venue.setBoolean(true);
        select_venue.setVisible(true);
        lblVenue.setText(null);
        dateChooser.setDate(null);
        cboTime.setSelectedItem(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
                
        if(window == false){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LguiEditConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LguiEditConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LguiEditConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LguiEditConsultation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LguiEditConsultation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cboTime;
    public com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lblVenue;
    // End of variables declaration//GEN-END:variables
}
